name: Docker Compose Pipeline

on:
  workflow_dispatch:  # Enables manual workflow dispatch from main branch
  #pull_request:
  #  branches:
  #    - main

jobs:
  docker-compose:
    name: Run Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: docker-compose up -d
