name: Docker Compose Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    name: Run Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: docker-compose up -d