Vagrant.configure('2') do |config|
  config.vm.provider :digital_ocean do |provider, override|
    provider.ssh_key_name = 'test-key'
    override.ssh.private_key_path = '~/.ssh/id_rsa'  # Path to your SSH private key
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    provider.token = 'dop_v1_6dae5b46dfaffe2ebeb7a6f4057ac13b7c0f1cc12ca2c2b7fb199785b3615bbd'
    provider.image = 'ubuntu-20-04-x64'
    provider.region = 'ams3'
    provider.size = 's-1vcpu-1gb'
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Update package list and install Go
    sudo apt-get update
    sudo apt-get -y upgrade
    sudo apt-get -y install golang-go

    # Set GOPATH; adjust this as needed
    echo "export GOPATH=$HOME/go" >> $HOME/.profile
    source $HOME/.profile

    # Copy or clone your application files to the VM
    git clone https://github.com/Eagles-DevOps/MiniTwit.git

    # Navigate to your app directory and build/run your Go app
    cd /MiniTwit
    cd /minitwit-web-app
    go run minitwit.go
  SHELL
end
