global:
  scrape_interval:     15s
  evaluation_interval: 15s 

scrape_configs:
  - job_name:       'scrape-minittwit-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:15001']
        labels:
          group: 'prod'
