global:
  scrape_interval:     15s
  evaluation_interval: 15s 

scrape_configs:
  - job_name:       'scrape-minittwit-api'
    scrape_interval: 5s
    static_configs:
<<<<<<< HEAD
=======
      - targets: ['prometheus:9090']

  - job_name:       'minitwit-api'

    scrape_interval: 5s

    static_configs:
>>>>>>> monitoring
      - targets: ['api:15001']
        labels:
          group: 'prod'
