services:
  minitwit_app:
    build: ../../minitwit-web-app
  environment:
      - POSTGRES_USER=minitwituser
      - POSTGRES_PW=minitwitpw
      - POSTGRES_HOST=postgres
      - POSTGRES_DB_NAME=minitwit
      - POSTGRES_PORT=5432
      - POSTGRES_DISABLE_SSL=true
  depends_on:
      - postgres
  command: ["./wait-for-it.sh", "postgres:5432", "--", "/usr/local/bin/app"]

  minitwit_api:
    build: ../../minitwit-api
    environment:
      - SQLITEPATH=./minitwit.db
      - POSTGRES_USER=minitwituser
      - POSTGRES_PW=minitwitpw
      - POSTGRES_HOST=postgres
      - POSTGRES_DB_NAME=minitwit
      - POSTGRES_PORT=5432
      - ALLOWMIGRATION=true
      - DBTYPE=postgres
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "/minitwit/app"]

#Just for shadowing
  watchtower:
    container_name: watchtower
    image: hello-world
    restart: 'no'
    command: ""

  postgres:
    #hostname: postgres.db
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - '5432:5432'
    command: -c 'max_connections=22'
    environment:
      POSTGRES_USER: minitwituser
      POSTGRES_PASSWORD: minitwitpw
      POSTGRES_DB: minitwit

