name: Automated Release

on:
  schedule:
    - cron:  '50 21 * * 4'  #runs every Thursday at 21:50

  push:
    branches: 
      - automated-release

  workflow_dispatch:


jobs: 
  release: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out Code
        uses: actions/checkout@v4

      - name: Bump version and create tag
        id: tag_step
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))

          if [[ $latest_tag =~ ^v([0-9]+)$ ]]; then
              version_number=${BASH_REMATCH[1]}
              ((version_number++))
              new_tag="v$version_number"

              git config --global user.name ${{ secrets.BOT_USERNAME }}
              git config --global user.email ${{ secrets.BOT_EMAIL }}

              git branch
              git fetch
              git tag $new_tag

              git push $new_tag
              echo "New tag: $new_tag"
              echo "incremented_tag=$new_tag" >> "$GITHUB_OUTPUT"
          else
              echo "Error: Latest tag format is unexpected: $latest_tag"
              exit 1
          fi

      - name: Check new tag value
        run: |
          echo "New incremented tag: ${{ steps.tag_step.outputs.incremented_tag }}"

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "${{ steps.tag_step.outputs.incremented_tag }}"
          prerelease: false
          title: "Release ${{ steps.tag_step.outputs.incremented_tag }}"