name: Build and deploy 

on:
  push:
    branches:
      - terra 

env:
  # The Github container registry
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push docker image app
        run: | 
          cd ./minitwit-web-app/
          docker build -t ghcr.io/eagles-devops/app:latest .
          docker push ghcr.io/eagles-devops/app:latest
      
      - name: Build and push docker image api
        run: | 
          cd ./minitwit-web-app/
          docker build -t ghcr.io/eagles-devops/api:latest .
          docker push ghcr.io/eagles-devops/api:latest
      
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_KEY: ${{ secrets.VIKTORIA_PRIVATE_KEY }}

      - name: Deploy to server app
        run: >
          ssh root@146.190.30.11 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no
          '/docker-project/deploy.sh'
      
      - name: Deploy to server api
        run: >
          ssh root@146.190.22.184 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no
          '/docker-project/deploy.sh'
      


