name: ci-cd

on:
  push:
    branches:
      - terra
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # https://github.com/docker/metadata-action
      - name: Extract Docker Metadata for app
        id: meta-app
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/app
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Extract Docker metadata for API
        id: meta-api
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/api
          flavor: |
            latest=true
          tags: |
            type=sha

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image for app
        uses: docker/build-push-action@v4
        with:
          context: ./minitwit-web-app
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image for api
        uses: docker/build-push-action@v4
        with:
          context: ./minitwit-web-app
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/terraform
          chmod 600 ~/.ssh/terraform
        env:
          SSH_KEY: ${{ secrets.VIKTORIA_PRIVATE_KEY }}

      - name: Deploy to server app
        run: >
          ssh root@164.90.205.60 -i ~/.ssh/terraform -o StrictHostKeyChecking=no 'sh /tmp/provision.sh'
      
      - name: Deploy to server api
        run: >
          ssh root@68.183.13.240 -i ~/.ssh/terraform -o StrictHostKeyChecking=no 'sh /tmp/provision.sh'

      


