name: Digital Ocean deployment

#comment

on:
  push:
    branches:
      - dploy

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        run: |
          sudo apt update
          sudo apt install -y golang

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Main app
        uses: docker/build-push-action@v2
        with:
          context: ./minitwit-web-app
          file: ./minitwit-web-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/minitwit_main:latest

      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: ./minitwit-api
          file: ./minitwit-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/minitwit_api:latest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run : |
          terraform init

      - name: Terraform plan
        run: |
          terraform plan
        env:
          TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
