name: Linters

on:
  push:
    branches:
      - 230-add-linters

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest