name: Linters

on:
  push:
    branches:
      - 230-add-linters

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install  GoKart Linter
        run : |
          go install github.com/praetorian-inc/gokart@latest

      - name: Run GoKart
        run: |
          cd minitwit-web-app
          gokart scan
        