name: Linters

on:
  push:
    branches:
      - 230-add-linters
  workflow_dispatch: 

jobs:
  StaticCheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: API app
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./minitwit-api
        continue-on-error: true

      - name: WEB app
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./minitwit-web-app
        continue-on-error: true



  DockerFileCheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker file - WEB app
        run: |
          cd ./minitwit-web-app
          docker run --rm -i -e HADOLINT_FORMAT=tty hadolint/hadolint < Dockerfile
        continue-on-error: true

      - name: Docker file - API app
        run: |
          cd ./minitwit-api
          docker run --rm -i -e HADOLINT_FORMAT=tty hadolint/hadolint < Dockerfile
        continue-on-error: true


  SourceCode: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run go vet
        run: |
          cd ./minitwit-web-app
          go vet ./...

      - name: Run go vet
        run: |
          cd ./minitwit-api
          go vet ./...