name: Linters

on:
  push:
    branches:
      - 230-add-linters

jobs:
  StaticCheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: API app
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./minitwit-api
        continue-on-error: true

      - name: WEB app
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./minitwit-web-app
        continue-on-error: true



  DockerFileCheck:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Log into Docker
          uses: docker/login-action@v3
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Hadolint
          run: |
            cd ./minitwit-web-app
            docker run --rm -i -e HADOLINT_FORMAT=tty hadolint/hadolint < Dockerfile
          continue-on-error: true