name: Linters

on:
  push:
    branches:
      - 230-add-linters

jobs:
  StaticCheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: API app
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./minitwit-api
        continue-on-error: true

      - name: WEB app
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./minitwit-web-app
        continue-on-error: true



  DockerFileCheck:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Hadolint
          run: |
            cd ./minitwit-web-app
            docker run -i hadolint/hadolint --format tty < Dockerfile
          continue-on-error: true